title: Aaron's Learning
logo: /assets/img/logo.png
description: A showcase of my work on Data Science, Machine Learning and Neural Networks
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
future: true
timezone: MD
